### ISSUE TITLE
response: Remove "Hello World" response from the bot

### ISSUE THREAD

**Issue by RudraNilBasu** [PhoenixRRDS/AIRYL#10]
Post https://github.com/PhoenixRRDS/AIRYL/commit/1af0d4f26033b6ff79f4d73ce9f1ab6a750f116d the bot returns 2 responses for each query from the user, one is the default "Hello World" response and the other one is the required response. The first response needs to be deleted.

**Comment by mouri11** [comment]
https://pastebin.com/7rXEYdMj
patch for issue #15

**Comment by RudraNilBasu** [comment]
No need to change the gradle files (both the project and the app). Also, `apps/libs/Ab.jar` was added back in https://github.com/PhoenixRRDS/AIRYL/commit/eebefea9d91f7fa82fe227213a39edda977ff4a1

**Comment by mouri11** [comment]
New patch with above changes : https://pastebin.com/JeBETJj9

**Comment by RudraNilBasu** [comment]
Looks good 👍 will merge it later today
