### ISSUE TITLE
UI: EditText should be on the bottom of the screen

### ISSUE THREAD

**Issue by RudraNilBasu** [PhoenixRRDS/AIRYL#12]

**Comment by mouri11** [comment]
https://pastebin.com/HwpSWSxP
patch for issue #12

**Comment by RudraNilBasu** [comment]
@mouri11 looks good, just a few things:
* Can you change the shortlog of the patch ("activity_main" will be good)
* A "fixes: #<issue_link>" statement in the commit message to indicate which issue is being dealt with. 

example: https://github.com/PhoenixRRDS/AIRYL/commit/1af0d4f26033b6ff79f4d73ce9f1ab6a750f116d

**Comment by mouri11** [comment]
Please check the new link. Thanks.
